name: C++ Linter and Formatter Check

on:
  push:
  pull_request:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run C++ linter (clang-format check + clang-tidy)
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''

      - name: Fail if lint or format errors found
        if: steps.linter.outputs.checks-failed != '0'
        run: exit 1
